# Generated by Django 6.0.3 on 2026-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_restaurant_cuisine_restaurant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant_images/default.jpg', upload_to='restaurant_images/'),
        ),
    ]
