# Generated by Django 6.0.3 on 2026-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_table_alter_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='static_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
