# Generated by Django 6.0.3 on 2026-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_restaurant_image_restaurant_static_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='static_image',
            field=models.ImageField(blank=True, upload_to='restaurant_images/'),
        ),
    ]
